#!/bin/sh
# Xcode Cloud post-clone script.
#
# Capacitor's iOS Swift Package Manager integration
# (ios/App/CapApp-SPM/Package.swift) references its plugins by *local*
# file-system path into node_modules - e.g.
# "../../../node_modules/@capacitor/app" - rather than a registry package.
# Xcode Cloud only clones the git repo; it never runs `npm install` on its
# own, so those node_modules directories don't exist yet by the time Xcode
# Cloud tries to resolve Swift packages, and the build fails at "Could not
# resolve package dependencies" before any of our code even compiles.
#
# Xcode Cloud automatically runs any executable script named
# ci_post_clone.sh that it finds in a ci_scripts folder next to the
# .xcodeproj, immediately after cloning the repo and before package
# resolution - so installing npm dependencies here is exactly what's needed
# to make those local SPM package paths resolve.
#
# Xcode Cloud's build images don't include Node.js/npm by default (this bit
# a first attempt at this script: `npm ci` alone failed with "command not
# found", exit 127) - Homebrew is available though, so install Node via
# brew first and link it onto PATH before touching npm.
#
# Node 20 was tried first and installed fine, but the Capacitor CLI (used
# below via `cap sync ios`) requires Node >=22 and refused to run under 20
# ("[fatal] The Capacitor CLI requires NodeJS >=22.0.0") - so this installs
# 22 instead.
set -e
set -x

# This script lives at ios/App/ci_scripts/, so the repo root is three
# directories up.
cd "$(dirname "$0")/../../.."

# Check for an existing node new enough (>=22), not just presence - a
# stale/cached image with an older node on PATH should still trigger a
# reinstall rather than silently reusing something too old.
node_major=0
if command -v node >/dev/null 2>&1; then
  node_major=$(node -v | sed 's/^v//' | cut -d. -f1)
fi
if [ "$node_major" -lt 22 ]; then
  echo "ci_post_clone.sh: node ${node_major:-missing} found, need >=22 - installing via Homebrew..."
  export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
  brew install node@22
  brew link node@22 --force --overwrite
fi

node -v
npm -v

echo "ci_post_clone.sh: installing npm dependencies so Capacitor's local SPM packages resolve..."
npm ci

# ios/App/App/capacitor.config.json, config.xml, and the App/App/public web
# assets folder are all listed in ios/.gitignore - Capacitor treats them as
# build output regenerated by `cap sync`, not something to hand-commit, so
# they simply don't exist in a fresh git clone. Locally this is invisible
# because your Mac already has them on disk from a previous `cap sync` you
# ran yourself - but Xcode Cloud clones fresh every time, so without this
# step its Xcode project references files that were never there, and the
# archive fails with "couldn't be opened because there is no such file".
#
# `npm run build` needs the Supabase URL/anon key as env vars (same ones
# the GitHub Pages deploy workflow uses) to bake into the web bundle -
# without them the archive will still succeed, but the shipped app won't be
# able to reach Supabase. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY
# as Environment Variables on this Xcode Cloud workflow (App Store Connect
# -> Xcode Cloud -> your workflow -> Environment) if they aren't already.
echo "ci_post_clone.sh: building the web app..."
npm run build

echo "ci_post_clone.sh: syncing web build + regenerating Capacitor's native config..."
npx cap sync ios
